name: CI
on: [push, pull_request]

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@0.1.0

  tests:
    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - sdolenc/testing-has:debian # uses debian:buster-20200327-slim which is debian 10.3
          - sdolenc/testing-has:ubuntu16 # uses ubuntu:xenial-20200212 which is ubuntu 16.04

    container: ${{ matrix.container }}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: unit tests
        run: make test
        shell: bash

  testE2E:
    name: end-to-end tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - sdolenc/testing-has:ubuntu # uses ubuntu:bionic-20200311 which is ubuntu 18.04
          - sdolenc/testing-has:alpine # uses bash:5.0.16 which is alpine 3.11

    container: ${{ matrix.container }}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Run e2e Tests
        run: bats -t ./tests/test_all.bats
        shell: bash